export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const EVENTFUL_LOADING = "EVENTFUL_LOADING";
export const GET_EVENTFULS = "GET_EVENTFULS";
export const GET_EVENTFUL = "GET_EVENTFUL";
export const ADD_EVENTFUL = "ADD_EVENTFUL";
export const DELETE_EVENTFUL = "DELETE_EVENTFUL";

